/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ./Oscilloscope.h.
 */

public class Constants  {
    public static final byte NREADINGS = 6;
    public static final byte ITEM = 7;
    public static final short DEFAULT_INTERVAL = 256;
    public static final byte PACKET_SIZE = 56;
    public static final short AM_OSCILLOSCOPE = 147;
}
